# This workflow will create wheels files for all major distros for several versions of python.
# This only triggers on release tags.

name: Release-Wheels

on:
  release:
    types: 
      - published
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
        
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build_wheels:
    name: Build wheel for py-abi3-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        python: [313]
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          # Window 64 bit
          - os: windows-latest
            platform_id: win_amd64
            sdist:

          # Linux 64 bit manylinux2014
          - os: ubuntu-latest
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
            sdist: --sdist

          # MacOS - latest is now arm64, no longer x86_64
          - os: macos-latest
            platform_id: macosx_arm64
            sdist: 
    steps:
      - uses: actions/checkout@v4
      - name: Cache downloaded files
        id: cache-kete
        uses: actions/cache@v4
        env:
          cache-name: cache-kete
        with:
          # kete stores all files in `~/.kete/` by default
          path: ~/.kete
          # These files are valid long term, and are not expected to change
          # between runs. So there is no need to a changing name.
          key: kete-cache
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install maturin
      - name: Build wheels
        run: python3 -m maturin build --release --out wheelhouse ${{ matrix.sdist }}
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-cp-${{ matrix.platform_id }}
          path: ./wheelhouse/*.whl
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-cp-sdist
          path: ./wheelhouse/*.tar.gz
  publish-to-pypi:
    name: Publish Kete to PyPI
    needs:
      - build_wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/kete
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          path: dist
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
